using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Idevs.Generators.Abstractions.Emission;

/// <summary>
/// Fluent C# source builder used by Idevs source generators. Manages
/// indentation, namespace scope, usings deduplication, and class/method
/// opening/closing. Output is deterministic — equal inputs always produce
/// equal output, suitable for snapshot testing.
/// </summary>
public sealed class IdevsSourceWriter
{
    private readonly List<string> _lines = new();
    private readonly SortedSet<string> _usings = new(StringComparer.Ordinal);
    private bool _includeFileHeader;
    private string? _namespace;
    private int _indent;
    private readonly Stack<string> _scopeStack = new();

    public IdevsSourceWriter WithFileHeader()
    {
        _includeFileHeader = true;
        return this;
    }

    public IdevsSourceWriter WithNamespace(string ns)
    {
        if (string.IsNullOrEmpty(ns)) throw new ArgumentException("Namespace cannot be empty", nameof(ns));
        _namespace = ns;
        return this;
    }

    public IdevsSourceWriter WithUsings(params string[] namespaces)
    {
        foreach (var ns in namespaces ?? Array.Empty<string>())
        {
            if (!string.IsNullOrEmpty(ns)) _usings.Add(ns);
        }
        return this;
    }

    public IdevsSourceWriter OpenClass(string name, bool isStatic = false, bool isPartial = false)
    {
        var modifiers = (isStatic ? "static " : "") + (isPartial ? "partial " : "");
        AppendIndentedLine($"public {modifiers}class {name}");
        AppendIndentedLine("{");
        _indent++;
        _scopeStack.Push("class");
        return this;
    }

    public IdevsSourceWriter CloseClass()
    {
        if (_scopeStack.Count == 0 || _scopeStack.Peek() != "class")
            throw new InvalidOperationException("CloseClass called without matching OpenClass.");
        _indent--;
        AppendIndentedLine("}");
        _scopeStack.Pop();
        return this;
    }

    public IdevsSourceWriter OpenMethod(string signature)
    {
        AppendIndentedLine(signature);
        AppendIndentedLine("{");
        _indent++;
        _scopeStack.Push("method");
        return this;
    }

    public IdevsSourceWriter CloseMethod()
    {
        if (_scopeStack.Count == 0 || _scopeStack.Peek() != "method")
            throw new InvalidOperationException("CloseMethod called without matching OpenMethod.");
        _indent--;
        AppendIndentedLine("}");
        _scopeStack.Pop();
        return this;
    }

    public IdevsSourceWriter AppendLine(string line = "")
    {
        AppendIndentedLine(line);
        return this;
    }

    public IdevsSourceWriter AppendRaw(string raw)
    {
        _lines.Add(raw);
        return this;
    }

    public SourceText ToSourceText()
    {
        var sb = new StringBuilder();
        if (_includeFileHeader)
        {
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
        }

        foreach (var u in _usings) sb.AppendLine($"using {u};");
        if (_usings.Count > 0) sb.AppendLine();

        if (!string.IsNullOrEmpty(_namespace))
        {
            sb.AppendLine($"namespace {_namespace};");
            sb.AppendLine();
        }

        foreach (var line in _lines) sb.AppendLine(line);

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private void AppendIndentedLine(string line)
    {
        if (line.Length == 0) _lines.Add("");
        else _lines.Add(new string(' ', _indent * 4) + line);
    }
}
