//HintName: IdevsServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Idevs.Extensions;
using Microsoft.Extensions.DependencyInjection;

namespace Idevs.Generated;

public static class IdevsServiceRegistrations
{
    public static IServiceCollection AddIdevsServices(this IServiceCollection services)
    {
        services.AddIdevsCorelibCore();

        services.AddScoped<global::Demo.ICustomerRepository, global::Demo.CustomerRepository>();

        return services;
    }
}
