//HintName: IdevsServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Idevs.Extensions;
using Microsoft.Extensions.DependencyInjection;

namespace Idevs.Generated;

public static class IdevsServiceRegistrations
{
    public static IServiceCollection AddIdevsServices(this IServiceCollection services)
    {
        services.AddIdevsCorelibCore();

        services.AddScoped<global::Demo.IAlphaRepository, global::Demo.AlphaRepository>();
        services.AddScoped<global::Demo.IMidRepository, global::Demo.MidRepository>();
        services.AddScoped<global::Demo.IZetaRepository, global::Demo.ZetaRepository>();

        return services;
    }
}
