//HintName: IdevsServiceRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Idevs.Extensions;
using Microsoft.Extensions.DependencyInjection;

namespace Idevs.Generated;

public static class IdevsServiceRegistrations
{
    public static IServiceCollection AddIdevsServices(this IServiceCollection services)
    {
        services.AddIdevsCorelibCore();
        services.AddIdevsCorelibLegacyScan();

        return services;
    }
}
